# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr: none
trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  webAppName: 'wavelengthcontrollerhub'

steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'appserviceconnection'
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az webapp show --name $(webAppName) --resource-group Maingroup
      powerShellErrorActionPreference: 'silentlyContinue'
    displayName: 'WebApp Details'
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'appserviceconnection'
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az webapp log deployment show --name $(webAppName) --resource-group Maingroup
      powerShellErrorActionPreference: 'silentlyContinue'
    displayName: 'WebApp Last Log'
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'appserviceconnection'
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az webapp log deployment show --name $(webAppName) --resource-group Maingroup
      powerShellErrorActionPreference: 'silentlyContinue'
    displayName: 'WepApp Log History'