# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr: none
trigger: none

pool:
  vmImage: ubuntu-latest

steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'appserviceconnection'
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az webapp log tail --resource-group Maingroup
      powerShellErrorActionPreference: 'silentlyContinue'
