# Generated by Django 5.2.5 on 2025-09-30 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0004_productcategory_productrange_product_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=3.98, max_digits=8),
        ),
    ]
