# Generated by Django 5.2.5 on 2025-09-30 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0005_alter_product_sale_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Product Category', 'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AlterModelOptions(
            name='productrange',
            options={'verbose_name': 'Product Range', 'verbose_name_plural': 'Product Ranges'},
        ),
    ]
