# Generated by Django 5.2.5 on 2025-09-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0007_product_tagline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tagline',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
