# Generated by Django 5.2.5 on 2025-09-30 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0008_alter_product_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='overview',
            field=models.CharField(default='One of finest products.', max_length=64),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.CharField(default='No specifications', max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(default='No description', max_length=1024),
        ),
    ]
