# Generated by Django 5.2.5 on 2025-09-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0009_product_overview_product_specifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='No description', max_length=1024),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.TextField(default='No specifications', max_length=256),
        ),
    ]
