# Generated by Django 5.2.5 on 2025-09-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0010_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='overview',
            field=models.CharField(default='One of the finest product.', max_length=64),
        ),
    ]
