# Generated by Django 5.2.5 on 2025-10-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0011_alter_product_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='No description', max_length=2048),
        ),
        migrations.AlterField(
            model_name='product',
            name='overview',
            field=models.TextField(default='One of the finest product.', max_length=512),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.TextField(default='No specifications', max_length=2048),
        ),
    ]
