# Generated by Django 5.2.5 on 2025-10-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0012_alter_product_description_alter_product_overview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
