# Generated by Django 5.2.7 on 2025-10-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storefront", "0014_productcolor_productsize"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="colors",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="storefront.productcolor"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="sizes",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="storefront.productsize"
            ),
        ),
    ]
