# Generated by Django 5.2.5 on 2025-10-12 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0014_product_average_rating_product_reviews_count_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='author_email',
        ),
        migrations.RemoveField(
            model_name='review',
            name='author_name',
        ),
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.TextField(max_length=2000),
        ),
    ]
