# Generated by Django 5.2.5 on 2025-10-12 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0015_remove_review_author_email_remove_review_author_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reviews_count',
        ),
    ]
