# Generated by Django 5.2.5 on 2025-10-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0016_remove_product_average_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
