# Generated by Django 5.2.5 on 2025-10-17 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0009_contactmessage'),
        ('storefront', '0018_add_user_fk_to_review'),
    ]

    operations = [
    ]
