# Generated by Django 5.2.5 on 2025-10-18 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0024_genericuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genericuser',
            options={'verbose_name': 'Generic User', 'verbose_name_plural': 'Generic Users'},
        ),
        migrations.AddField(
            model_name='customer',
            name='generic_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storefront.genericuser'),
        ),
    ]
