# Generated by Django 5.2.5 on 2025-10-18 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0025_alter_genericuser_options_customer_generic_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.AlterField(
            model_name='customer',
            name='generic_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='storefront.genericuser'),
        ),
    ]
