# Generated by Django 5.2.5 on 2025-10-18 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0026_remove_customer_user_alter_customer_generic_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericuser',
            name='previous_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
