# Generated by Django 5.2.5 on 2025-10-18 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0028_remove_customer_generic_user_customer_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='zip_code',
            new_name='postcode',
        ),
    ]
