# azure-pipelines.yml
trigger:
  branches:
    include:
      - search

pool:
  vmImage: ubuntu-latest

variables:
  PYTHON_VERSION: '3.12'
  WORKDIR: 'ecommerce'
  DJANGO_SETTINGS_MODULE: 'ecommerce.settings'

stages:
- stage: CI
  displayName: CI - Lint & Test
  jobs:
  - job: build_test
    displayName: Lint & Pytest
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(PYTHON_VERSION)'
      displayName: 'Use Python $(PYTHON_VERSION)'

    - script: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
      displayName: 'Install dependencies'

    - script: |
        export DJANGO_SETTINGS_MODULE=$(DJANGO_SETTINGS_MODULE)
        python manage.py migrate --noinput
        pytest -q
      displayName: 'Run migrations & pytest'
      workingDirectory: $(WORKDIR)