# parameters:
---
  parameters:
    - name: PythonVersion
      type: string 
      values:
        - '3.9'
        - '3.10'
        - '3.11'
        - '3.12'
        - '3.13'
      default: '3.11'

  variables:
    azureServiceConnection: 'appserviceconnection'
    vmImageName: 'ubuntu-latest'
    webAppName: 'wavelengthcontrollerhub'
    projectRoot: $(System.DefaultWorkingDirectory)

  stages:
  # - stage: "LinterStage"
  #   displayName: "Linter Stage"
  #   pool:
  #     vmImage: $(vmImageName)
  #   jobs:
  #   - job: InstallPython
  #     steps:
  #       - task: UsePythonVersion@0
  #         inputs:
  #           versionSpec: ${{ parameters.PythonVersion }}
  #         displayName: 'Use Python ${{ parameters.PythonVersion }}'
  #   - job: RunLinters
  #     dependsOn: InstallPython
  #     steps:
  #       - script: |
  #           python -m pip install flake8
  #         displayName: "Install flake8"
  #       - script: |
  #           python -m pip install mypy
  #         displayName: "Install mypy"
  #       - bash: |
  #           echo "Running mypy linter..."
  #           python -m mypy . ; true
  #         displayName: "Linter Run (mypy)"
  #       - bash: |
  #           echo "Running flake8 linter..."
  #           python -m flake8 . ; true
  #         displayName: "Linter Run (flake8)"

  # - stage: "UnitTestingStage"
  #   displayName: "Unit Testing Stage"
  #   dependsOn: LinterStage
  #   pool:
  #     vmImage: $(vmImageName)
  #   jobs:
  #   - job: InstallPython
  #     steps:
  #       - task: UsePythonVersion@0
  #         inputs:
  #           versionSpec: ${{ parameters.PythonVersion }}
  #         displayName: 'Use Python ${{ parameters.PythonVersion }}'
  #   - job: RunUnitTests
  #     dependsOn: InstallPython
  #     steps:
  #       - script: |
  #             python -m pip install -r requirements.txt
  #           workingDirectory: $(projectRoot)
  #         displayName: "Install Python Depenencies"
  #       - bash: |
  #           echo "Running tests..."
  #           python ecommerce/manage.py test storefront; true
  #         workingDirectory: $(projectRoot)
  #         displayName: "Run Unit Tests"

  # - stage: "DeploymentApprovalStage"
  #   displayName: "Deployment Approval Stage"
  #   dependsOn: UnitTestingStage
  #   pool: server
  #   jobs:
  #   - job: DeploymentApprovalJob
  #     steps:
  #       - task: ManualValidation@1
  #         inputs:
  #           instructions: 'Please approve the deployment.'
  #           timeoutInMinutes: 5

  - stage: "BuildStage"
    displayName: "Build stage"
    # dependsOn: DeploymentApprovalStage
    jobs:
    - job: BuildJob
      pool:
        vmImage: $(vmImageName)
      steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: ${{ parameters.PythonVersion }}
        displayName: 'Use Python ${{ parameters.PythonVersion }}'
      - script: |
          python -m venv antenv
          source antenv/bin/activate
          python -m pip install --upgrade pip
          pip install setuptools
          pip install -r requirements.txt
        displayName: "Install requirements"
      - script: |
          python ecommerce/manage.py makemigrations
          python ecommerce/manage.py migrate
        workingDirectory: $(projectRoot)
        displayName: "Run Database Migrations"
      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: '$(projectRoot)'
          includeRootFolder: false
          archiveType: zip
          archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
          replaceExistingArchive: true
        displayName: 'Archive files (Create Artifact)'
      - publish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        artifact: drop
        displayName: 'Publish Artifact'
      - script: |
          pwd
          echo "ls -la ."
          ls -la .
          echo "ls -la Pipeline.Workspace $(Pipeline.Workspace)"
          ls -la $(Pipeline.Workspace)
          echo "ls -la $(Pipeline.Workspace)/drop"
          ls -la $(Pipeline.Workspace)/drop
          echo "Build ID: $(Build.BuildId).zip"
          echo "ls -la $(Build.ArtifactStagingDirectory)"
          ls -la $(Build.ArtifactStagingDirectory)
        workingDirectory: $(projectRoot)
        displayName: "List files"
      - task: AzureCLI@2
        inputs:
          azureSubscription: 'appserviceconnection'
          scriptType: 'pscore'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az --version
            az account show
            az webapp list
            az webapp list --query "[?name=='$(webAppName)']"
            az webapp show --name $(webAppName) --resource-group Maingroup
          powerShellErrorActionPreference: 'continue'
        displayName: 'Test Azure CLI Connection'

  - stage: DeployStage
    displayName: "Deploy Stage"
    dependsOn: BuildStage
    condition: succeeded()
    jobs:
    - job: DeploymentJob
      pool:
        vmImage: $(vmImageName)
      steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: ${{ parameters.PythonVersion }}
        displayName: 'Use Python ${{ parameters.PythonVersion }}'
      - download: current
        artifact: drop
        displayName: 'Download Artifact'
      - script: |
          pwd
          echo "ls -la ."
          ls -la .
          echo "ls -la Pipeline.Workspace $(Pipeline.Workspace)"
          ls -la $(Pipeline.Workspace)
          echo "ls -la $(Pipeline.Workspace)/drop"
          ls -la $(Pipeline.Workspace)/drop
          echo "Build ID: $(Build.BuildId).zip"
          echo "ls -la $(Build.ArtifactStagingDirectory)"
          ls -la $(Build.ArtifactStagingDirectory)
        workingDirectory: $(projectRoot)
        displayName: "List files"
      # - task: AzureWebApp@1
      #   displayName: 'Deploy Azure Web App : $(webAppName)'
      #   inputs:
      #     azureSubscription: $(azureServiceConnection)
      #     appName: $(webAppName)
      #     package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip
      #     startUpCommand: 'python manage.py runserver'
      - task: AzureWebApp@1
        inputs:
          azureSubscription: $(azureServiceConnection)
          appType: 'webAppLinux'
          appName: $(webAppName)
          deployToSlotOrASE: true
          resourceGroupName: 'Maingroup'
          slotName: 'production'
          package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
          runtimeStack: 'PYTHON|3.13'
          startUpCommand: 'python manage.py runserver'
        displayName: 'Deploy Azure Web App'

