# parameters:
---
  parameters:
    - name: PythonVersion
      type: string 
      values:
        - '3.9'
        - '3.10'
        - '3.11'
        - '3.12'
        - '3.13'
      default: '3.11'


  stages:
  - stage: "LinterStage"
    pool:
      vmImage: ubuntu-latest
    jobs:
    - job: InstallPython
      steps:
        - task: UsePythonVersion@0
          inputs:
            versionSpec: ${{ parameters.PythonVersion }}
          displayName: 'Use Python ${{ parameters.PythonVersion }}'
    - job: InstallLinters
      steps:
        - script: |
            python -m pip install flake8
          displayName: "Install Flake8"
        - script: |
            python -m pip install mypy
          displayName: "Install mypy"
    - job: RunLinters
      steps:
        - bash: |
            echo "Running linter..."
            pwd
            ll
            mypy ./
            flake8 ./
            # Add linter commands here
          displayName: "Linter Run"
  - stage: "Unit Testing Stage"
    pool:
      vmImage: ubuntu-latest
    jobs:
    - job: UnitTestsJob
      steps:
        - task: UsePythonVersion@0
          inputs:
            versionSpec: ${{ parameters.PythonVersion }}
          displayName: 'Use Python ${{ parameters.PythonVersion }}'
        - bash: |
            echo "Running Tests..."
            # Add Tests commands here
          displayName: 'UnitTestsJob'